# Generated by Django 3.1.3 on 2020-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='db_role',
            field=models.PositiveIntegerField(choices=[(0, 'Default'), (1, 'BB Product'), (2, 'Population')], default=0, verbose_name='\nFor which database you want to create this user.\nUse any one role:\n\n0 for Super Admin User.\n1 for BB Product User.\n2 for Population User.\nEnter your selection'),
        ),
    ]
