# Generated by Django 3.1.3 on 2020-11-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6)),
                ('product', models.CharField(max_length=255)),
                ('recorded', models.DateField()),
                ('org_user', models.CharField(max_length=255)),
                ('modified_user', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'BB-Product',
                'verbose_name_plural': 'BB-Products',
            },
        ),
    ]
